function [STDPlotSet] = S7_SetPlot (FigW,FigH,process,fDPLT)
% This function sets the properties for all the figure generated by SVEC
% The standard properties are saved so they can be restored later
% INPUT
% FigW [cm]   : figure width in centimeters
% FigH [cm]   : figure height in centimeter
% process [-] : process flag - 1 compression - 2 expansion
% fDPLT [-]   : plot display flag - 0 plots not displayed - 1 plots displayed
% 
% OUTPUT
% STDPlotSet  : struct of default properties of matlab plots

    %% PREAMBLE %%
    STDPlotSet = get(groot, 'default');  % save default figure settings
    
    %% FIGURE SIZE AND POSITION %%
    set (groot,'DefaultFigureUnit','centimeters'); % set figures unit to centimeters
    FigPos = [0,0,FigW,FigH];                      % create first attempt position vector for proxy figures
    figure('Visible','off','Position',FigPos)      % create proxy figure of correct size, but incorrect position
    movegui(gcf,'north');                          % place proxy fiure in top center position
    FigPos = get(gcf,'Position');                  % get position of proxy figure
    FigPos(2) = FigPos(2) - 0.3;                   % position adjustment
    close gcf                                      % close proxy pigure

    %% OTHER PROPERTIES %%
    set (groot,'DefaultFigureNumberTitle','off');        % disable default number in figure title
    set (groot,'DefaultFigurePosition',FigPos);          % set figure position and size
    set (groot,'DefaultFigurePaperUnits','centimeters'); % set sheet unit
    set (groot,'DefaultFigurePaperType','<custom>');     % set sheet type
    set (groot,'DefaultFigurePaperSize',FigPos(3:end));  % set sheet dimension
    if process ==1                                       % set legend location
        set (groot,'DefaultLegendLocation','northwest');
    else
        set (groot,'DefaultLegendLocation','northeast');
    end
    if fDPLT == 1                                        % set visibility property
        set (groot,'DefaultFigureVisible', 'on');
    else
        set (groot,'DefaultFigureVisible', 'off');
    end
    
end